### ISSUE TITLE
Bump dough-ruby ->  to latest (5.7.0)

### ISSUE THREAD

**Issue by ourmaninamsterdam** [moneyadviceservice/rad#191]
RAD is pegged to a [specific Dough commit](https://github.com/moneyadviceservice/rad/blob/b9ed03fc4ea13d8b0c0a24776155f2aad436faa6/Gemfile#L15) and could be following the latest build.

@alexwllms  Do you know the reason for this being pegged?

**Comment by neoeno** [comment]
This was completed recently :+1:
